on: push
jobs:
  build-project:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name : Checkout code from GitHub
      uses: actions/checkout@v4
    - name: Login to Docker Hub      
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: matosauer/contoso-spaces-web:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}